"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2025-01-18 01:32:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('islamic_characters',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('arabic_name', sa.String(length=200), nullable=False),
        sa.Column('english_name', sa.String(length=200), nullable=True),
        sa.Column('title', sa.String(length=300), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('birth_year', sa.Integer(), nullable=True),
        sa.Column('death_year', sa.Integer(), nullable=True),
        sa.Column('era', sa.String(length=100), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('sub_category', sa.String(length=100), nullable=True),
        sa.Column('full_story', sa.Text(), nullable=True),
        sa.Column('key_achievements', sa.JSON(), nullable=True),
        sa.Column('lessons', sa.JSON(), nullable=True),
        sa.Column('quotes', sa.JSON(), nullable=True),
        sa.Column('profile_image', sa.String(length=500), nullable=True),
        sa.Column('gallery', sa.JSON(), nullable=True),
        sa.Column('audio_stories', sa.JSON(), nullable=True),
        sa.Column('animations', sa.JSON(), nullable=True),
        sa.Column('timeline_events', sa.JSON(), nullable=True),
        sa.Column('birth_place', sa.String(length=200), nullable=True),
        sa.Column('death_place', sa.String(length=200), nullable=True),
        sa.Column('locations', sa.JSON(), nullable=True),
        sa.Column('related_characters', sa.JSON(), nullable=True),
        sa.Column('views_count', sa.Integer(), default=0),
        sa.Column('likes_count', sa.Integer(), default=0),
        sa.Column('shares_count', sa.Integer(), default=0),
        sa.Column('is_featured', sa.Boolean(), default=False),
        sa.Column('is_verified', sa.Boolean(), default=False),
        sa.Column('verification_source', sa.String(length=500), nullable=True),
        sa.Column('verification_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False, unique=True),
        sa.Column('email', sa.String(length=255), nullable=False, unique=True),
        sa.Column('full_name', sa.String(length=200), nullable=True),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('is_superuser', sa.Boolean(), default=False),
        sa.Column('language', sa.String(length=10), default='ar'),
        sa.Column('theme', sa.String(length=20), default='light'),
        sa.Column('notification_settings', sa.JSON(), nullable=True),
        sa.Column('total_stories_completed', sa.Integer(), default=0),
        sa.Column('total_time_spent', sa.Integer(), default=0),  # in minutes
        sa.Column('streak_days', sa.Integer(), default=0),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('last_active', sa.DateTime(timezone=True), onupdate=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_progress',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('character_id', sa.Integer(), nullable=False),
        sa.Column('current_chapter', sa.Integer(), default=0),
        sa.Column('total_chapters', sa.Integer(), nullable=True),
        sa.Column('completion_percentage', sa.Float(), default=0.0),
        sa.Column('is_completed', sa.Boolean(), default=False),
        sa.Column('bookmarked', sa.Boolean(), default=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=True),  # 1-5 stars
        sa.Column('last_position', sa.Integer(), nullable=True),  # For audio/video
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('time_spent', sa.Integer(), default=0),  # in seconds
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.ForeignKeyConstraint(['character_id'], ['islamic_characters.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False, unique=True),
        sa.Column('arabic_name', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('icon', sa.String(length=100), nullable=True),
        sa.Column('color', sa.String(length=20), nullable=True),
        sa.Column('sort_order', sa.Integer(), default=0),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_lessons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.String(length=10), nullable=False, unique=True),
        sa.Column('character_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('verse', sa.JSON(), nullable=True),
        sa.Column('hadith', sa.JSON(), nullable=True),
        sa.Column('reflection_question', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['character_id'], ['islamic_characters.id']),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('daily_lessons')
    op.drop_table('content_categories')
    op.drop_table('user_progress')
    op.drop_table('users')
    op.drop_table('islamic_characters')
